# This workflow will build a test Java + TestNG + Appium + BrowserStack project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Run

on:
  workflow_dispatch:
    branches: [ ga_script ]
    inputs:
      test_tag:
        description: 'Tags to run'
        required: true
        default: '@example_tag'
      build_name:
        description: 'build name of given application'
        required: false
        default: 'CPW'
      browser_name:
        description: 'Browser name'
        required: true
        default: 'chrome'
      browser_type:
        description: 'Browser type'
        required: true
        default: 'desktop'
      environment:
        description: 'Environment name'
        required: false
        default: 'beta'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run:
        SECRET_NAME=$(secrets.CPW_${{github.event.inputs.environment}}_LINK)
        mvn clean test -DstartUrl=${{SECRET_NAME}} -Daquality.buildName="${{github.event.inputs.build_name}}" -Daquality.token=${{secrets.TRACKING_API_TOKEN}} -Daquality.suiteName="${{github.event.inputs.test_tag}}" -Daquality.environment="${{github.event.inputs.browser_name}}" -Dcredentials.LYRASIS.${{secrets.BookCard}}=${{secrets.BookPin}} -Dcredentials.LYRASIS.${{secrets.BookCardLyrasis2}}=${{secrets.BookPinLyrasis2}} -Dcredentials."The New York Public Library".${{secrets.BookCardNYPL}}=${{secrets.BookPinNYPL}} -DremoteConnectionUrl=${{secrets.remoteConnectionUrl}} -DbrowserName=${{github.event.inputs.browser_name}} -Dcucumber.options="--tags '(${{github.event.inputs.test_tag}}) and @${{github.event.inputs.browser_type}}'" -Denvironment=${{github.event.inputs.environment}}
    - name: Generate Allure Report
      uses: afiore/action-allure-report@v0.1.0
      if: success() || failure()
    - name: Upload report
      uses: actions/upload-artifact@v2.1.4
      with:
        name: allure-report
        path: allure-report/
      if: success() || failure()
