# This workflow will build a test Java + TestNG + Appium + BrowserStack project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Test Run

on:
  schedule:
    - cron:  '0 23 * * 0-4'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      env:
        ENVIRONMENT_URL_NAME: CPW_BETA_LINK
      run:
        mvn clean test -DstartUrl=${{secrets[env.ENVIRONMENT_URL_NAME]}} -Daquality.buildName="CPW" -Daquality.token=${{secrets.TRACKING_API_TOKEN}} -Daquality.suiteName="(@tier1 or @tier2 or @tier3)" -Daquality.environment="chrome" -Dcredentials.LYRASIS.${{secrets.BookCard}}=${{secrets.BookPin}} -Dcredentials."The New York Public Library".${{secrets.BookCardNYPL}}=${{secrets.BookPinNYPL}} -DremoteConnectionUrl=${{secrets.remoteConnectionUrl}} -DbrowserName=chrome -Dcucumber.options="--tags '((@tier1 or @tier2 or @tier3)) and @desktop'" -Denvironment=beta
    - name: Generate Allure Report
      uses: afiore/action-allure-report@v0.1.0
      if: success() || failure()
    - name: Upload report
      uses: actions/upload-artifact@v2.1.4
      with:
        name: allure-report
        path: allure-report/
      if: success() || failure()
